export const stripDiacritics = (value: string): string => {
  if (!value) return '';
  try {
    const noMarks = value.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const transliterationMap: Record<string, string> = {
      А: 'A',
      Б: 'B',
      В: 'V',
      Г: 'G',
      Д: 'D',
      Е: 'E',
      Ё: 'E',
      Ж: 'Zh',
      З: 'Z',
      И: 'I',
      Й: 'I',
      К: 'K',
      Л: 'L',
      М: 'M',
      Н: 'N',
      О: 'O',
      П: 'P',
      Р: 'R',
      С: 'S',
      Т: 'T',
      У: 'U',
      Ф: 'F',
      Х: 'Kh',
      Ц: 'Ts',
      Ч: 'Ch',
      Ш: 'Sh',
      Щ: 'Shch',
      Ы: 'Y',
      Ь: '',
      Ъ: '',
      Э: 'E',
      Ю: 'Yu',
      Я: 'Ya',
      а: 'a',
      б: 'b',
      в: 'v',
      г: 'g',
      д: 'd',
      е: 'e',
      ё: 'e',
      ж: 'zh',
      з: 'z',
      и: 'i',
      й: 'i',
      к: 'k',
      л: 'l',
      м: 'm',
      н: 'n',
      о: 'o',
      п: 'p',
      р: 'r',
      с: 's',
      т: 't',
      у: 'u',
      ф: 'f',
      х: 'kh',
      ц: 'ts',
      ч: 'ch',
      ш: 'sh',
      щ: 'shch',
      ы: 'y',
      ь: '',
      ъ: '',
      э: 'e',
      ю: 'yu',
      я: 'ya',
      ä: 'a',
      ö: 'o',
      ü: 'u',
      ß: 'ss',
      Ä: 'A',
      Ö: 'O',
      Ü: 'U',
      å: 'a',
      Å: 'A',
      ø: 'o',
      Ø: 'O',
      æ: 'ae',
      Æ: 'AE',
      ç: 'c',
      Ç: 'C',
      ñ: 'n',
      Ñ: 'N',
      ğ: 'g',
      Ğ: 'G',
      ş: 's',
      Ş: 'S',
      ł: 'l',
      Ł: 'L',
      đ: 'd',
      Đ: 'D',
      ő: 'o',
      Ő: 'O',
      ű: 'u',
      Ű: 'U',
    };

    return noMarks.replace(/[\u0400-\u04FF\u00C0-\u017F]/g, (char) => transliterationMap[char] ?? char);
  } catch {
    return value;
  }
};
